"use client";

import { createEventCollection, deleteEventCollection, renameEventCollection } from "@/lib/events/actions";
import type { EventCollection } from "@/lib/events/types";
import { PixelIcon } from "@/components/ui/pixel";

export function CollectionManager({ collections }: { collections: EventCollection[] }) {
  return <div className="mt-4 space-y-3"><form action={createEventCollection} className="grid grid-cols-[1fr_auto_auto] gap-2 border-2 border-dashed border-[var(--line)] bg-[var(--card)] p-2"><input aria-label="新项目名称" className="pixel-input min-w-0 py-2 text-sm" maxLength={30} name="name" placeholder="新建项目分类" required /><input aria-label="新项目颜色" className="size-10 border-2 border-[var(--line)] bg-[var(--card)] p-1" defaultValue="#8da77a" name="color" type="color" /><button className="pixel-button pixel-button-secondary min-h-10 px-3 text-xs" type="submit"><PixelIcon className="size-4" name="plus" />新建</button></form>{collections.length ? <div className="space-y-2">{collections.map((collection) => <div className="flex items-center gap-2 border-2 border-[var(--line)] bg-[var(--paper-deep)] p-2" key={collection.id}><form action={renameEventCollection} className="flex min-w-0 flex-1 items-center gap-2"><input name="id" type="hidden" value={collection.id} /><input aria-label={`修改 ${collection.name} 的颜色`} className="size-9 shrink-0 border-2 border-[var(--line)] bg-[var(--card)] p-1" defaultValue={collection.color} name="color" type="color" /><input aria-label={`修改分类 ${collection.name}`} className="pixel-input min-w-0 flex-1 py-2 text-sm" defaultValue={collection.name} maxLength={30} name="name" required /><button className="pixel-button pixel-button-secondary min-h-9 px-3 text-xs" type="submit">保存</button></form><form action={deleteEventCollection}><input name="id" type="hidden" value={collection.id} /><button aria-label={`删除分类 ${collection.name}`} className="min-h-9 px-2 text-sm font-bold text-[var(--brick)]" onClick={(event) => { if (!window.confirm(`删除“${collection.name}”分类？相关事件会变为未分类。`)) event.preventDefault(); }} type="submit"><PixelIcon className="size-4" name="archive" /></button></form></div>)}</div> : <p className="text-sm leading-6 text-[var(--soil)]">还没有分类；可直接在上面新建，或在创建事件时输入分类名称。</p>}</div>;
}
