import Link from "next/link";
import { BottomNav } from "@/components/layout/bottom-nav";
import { EVENT_STATUS_LABELS, EVENT_STATUSES } from "@/lib/events/types";
import { getTags } from "@/lib/events/queries";
import { parseSearchFilters, searchTimeline } from "@/lib/search/queries";
import { PageShell, PixelEmptyState, PixelIcon } from "@/components/ui/pixel";

export const dynamic = "force-dynamic";
function dateLabel(value: string) { const [year, month, day] = value.slice(0, 10).split("-"); return `${year}年${Number(month)}月${Number(day)}日`; }

export default async function SearchPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const filters = parseSearchFilters(await searchParams);
  const tags = await getTags();
  const hasSearch = Boolean(filters.q || filters.status || filters.tag || filters.from || filters.to || filters.important);
  const results = hasSearch ? await searchTimeline(filters) : [];
  return <PageShell><header className="pixel-paper flex items-end justify-between gap-4 p-5 sm:p-6"><div><p className="pixel-eyebrow">FIND A MEMORY</p><h1 className="pixel-title mt-2 text-3xl">翻找记录</h1></div><Link className="pixel-button pixel-button-secondary min-h-10 px-3 text-sm" href="/events">返回事件</Link></header><form action="/search" className="pixel-paper mt-7 space-y-4 p-4 sm:p-5"><div className="flex gap-2"><input className="pixel-input min-w-0 flex-1 text-base" defaultValue={filters.q} name="q" placeholder="事件名称、节点内容或标签" type="search" /><button aria-label="搜索" className="pixel-button pixel-button-primary min-h-12 px-3" type="submit"><PixelIcon className="size-5" name="search" /></button></div><div className="grid gap-3 sm:grid-cols-2"><select className="pixel-select text-sm" defaultValue={filters.status ?? ""} name="status"><option value="">全部状态</option>{EVENT_STATUSES.filter((status) => status !== "archived").map((status) => <option key={status} value={status}>{EVENT_STATUS_LABELS[status]}</option>)}</select><select className="pixel-select text-sm" defaultValue={filters.tag ?? ""} name="tag"><option value="">全部标签</option>{tags.map((tag) => <option key={tag} value={tag}>{tag}</option>)}</select><input className="pixel-input text-sm" defaultValue={filters.from ?? ""} name="from" type="date" /><input className="pixel-input text-sm" defaultValue={filters.to ?? ""} name="to" type="date" /></div><label className="flex min-h-11 items-center gap-2 text-sm font-bold text-[var(--soil)]"><input className="size-4" defaultChecked={filters.important === "1"} name="important" type="checkbox" value="1" />只看重要节点</label></form>{!hasSearch ? <div className="mt-8"><PixelEmptyState icon="search" title="翻开一本旧记录吧。">输入关键词，或选择一个筛选条件开始搜索。</PixelEmptyState></div> : results.length ? <section className="mt-8 space-y-3"><p className="pixel-eyebrow">找到 {results.length} 条记录</p>{results.map((result) => <Link className="pixel-card pixel-card-hover block p-4" href={result.result_type === "node" ? `/events/${result.event_id}#node-${result.node_id}` : `/events/${result.event_id}`} key={`${result.result_type}-${result.node_id ?? result.event_id}`}><div className="flex items-center justify-between gap-3 text-xs font-bold text-[var(--soil)]"><span>{result.result_type === "event" ? "事件" : "节点"} · {result.event_title}</span><span>{dateLabel(result.result_date)}</span></div><h2 className="pixel-title mt-2 text-lg">{result.title}</h2>{result.excerpt && <p className="mt-2 line-clamp-2 text-sm leading-6 text-[var(--soil)]">{result.excerpt}</p>}{result.is_important && <span className="pixel-chip mt-3 bg-[#f7d88b] text-[#7d5321]"><PixelIcon className="size-3" name="star" />重要节点</span>}</Link>)}</section> : <div className="mt-8"><PixelEmptyState icon="search" title="没有找到相符记录。">换个词或放宽筛选条件试试。</PixelEmptyState></div>}<BottomNav /></PageShell>;
}
